# Generated by Django 5.2 on 2025-07-28 10:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpatchcore', '0003_buildmodel_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSiteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpatchcore.sitemodel')),
            ],
        ),
        migrations.AddField(
            model_name='buildmodel',
            name='sub_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staticpatchcore.subsitemodel'),
        ),
        migrations.AddConstraint(
            model_name='subsitemodel',
            constraint=models.UniqueConstraint(fields=('site', 'url'), name='sub_site_site_url_unique'),
        ),
    ]
