# Generated by Django 5.2 on 2025-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpatchcore', '0004_subsitemodel_buildmodel_sub_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='public_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='public_info_url',
            field=models.CharField(default='/staticpatchsiteinfo', max_length=500),
        ),
    ]
