name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        architecture: x64
    - run: pip install -r requirements_dev.txt
    - run: black --check .
      working-directory: ./staticpatch
    - run: isort --check-only .
      working-directory: ./staticpatch
    - run: flake8 staticpatch
      working-directory: ./staticpatch
    - run: mypy --install-types --non-interactive .
      working-directory: ./staticpatch
